version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=platzi_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234567890
    ports:
      - '8000:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=platzi_store
      - MYSQL_ROOT_PASSWORD=1234567890
    ports:
      - '3001:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890
      - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
